export type LanguageProvider = "microsoft" | "deepl";

export interface LanguageOption {
  code: string;
  name: string;
  providers: LanguageProvider[];
  sourceOnly?: boolean;
}

const microsoftLanguages: Array<Omit<LanguageOption, "providers">> = [
  { code: "af", name: "Afrikaans" },
  { code: "am", name: "Amharic" },
  { code: "ar", name: "Arabic" },
  { code: "as", name: "Assamese" },
  { code: "az", name: "Azerbaijani" },
  { code: "ba", name: "Bashkir" },
  { code: "be", name: "Belarusian" },
  { code: "bg", name: "Bulgarian" },
  { code: "bho", name: "Bhojpuri" },
  { code: "bn", name: "Bangla" },
  { code: "bo", name: "Tibetan" },
  { code: "brx", name: "Bodo" },
  { code: "bs", name: "Bosnian" },
  { code: "ca", name: "Catalan" },
  { code: "cs", name: "Czech" },
  { code: "cy", name: "Welsh" },
  { code: "da", name: "Danish" },
  { code: "de", name: "German" },
  { code: "doi", name: "Dogri" },
  { code: "dsb", name: "Lower Sorbian" },
  { code: "dv", name: "Divehi" },
  { code: "el", name: "Greek" },
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "et", name: "Estonian" },
  { code: "eu", name: "Basque" },
  { code: "fa", name: "Persian" },
  { code: "fi", name: "Finnish" },
  { code: "fil", name: "Filipino" },
  { code: "fj", name: "Fijian" },
  { code: "fo", name: "Faroese" },
  { code: "fr", name: "French" },
  { code: "fr-CA", name: "French (Canada)" },
  { code: "ga", name: "Irish" },
  { code: "gl", name: "Galician" },
  { code: "gom", name: "Konkani" },
  { code: "gu", name: "Gujarati" },
  { code: "ha", name: "Hausa" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hne", name: "Chhattisgarhi" },
  { code: "hr", name: "Croatian" },
  { code: "hsb", name: "Upper Sorbian" },
  { code: "ht", name: "Haitian Creole" },
  { code: "hu", name: "Hungarian" },
  { code: "hy", name: "Armenian" },
  { code: "id", name: "Indonesian" },
  { code: "ig", name: "Igbo" },
  { code: "ikt", name: "Inuinnaqtun" },
  { code: "is", name: "Icelandic" },
  { code: "it", name: "Italian" },
  { code: "iu", name: "Inuktitut" },
  { code: "iu-Latn", name: "Inuktitut (Latin)" },
  { code: "ja", name: "Japanese" },
  { code: "ka", name: "Georgian" },
  { code: "kk", name: "Kazakh" },
  { code: "km", name: "Khmer" },
  { code: "kmr", name: "Kurdish (Northern)" },
  { code: "kn", name: "Kannada" },
  { code: "ko", name: "Korean" },
  { code: "ks", name: "Kashmiri" },
  { code: "ku", name: "Kurdish (Central)" },
  { code: "ky", name: "Kyrgyz" },
  { code: "lb", name: "Luxembourgish" },
  { code: "ln", name: "Lingala" },
  { code: "lo", name: "Lao" },
  { code: "lt", name: "Lithuanian" },
  { code: "lug", name: "Ganda" },
  { code: "lv", name: "Latvian" },
  { code: "lzh", name: "Chinese (Literary)" },
  { code: "mai", name: "Maithili" },
  { code: "mg", name: "Malagasy" },
  { code: "mi", name: "Maori" },
  { code: "mk", name: "Macedonian" },
  { code: "ml", name: "Malayalam" },
  { code: "mn-Cyrl", name: "Mongolian (Cyrillic)" },
  { code: "mn-Mong", name: "Mongolian (Traditional)" },
  { code: "mni", name: "Manipuri" },
  { code: "mr", name: "Marathi" },
  { code: "ms", name: "Malay" },
  { code: "mt", name: "Maltese" },
  { code: "mww", name: "Hmong Daw" },
  { code: "my", name: "Myanmar (Burmese)" },
  { code: "nb", name: "Norwegian Bokmal" },
  { code: "ne", name: "Nepali" },
  { code: "nl", name: "Dutch" },
  { code: "nso", name: "Sesotho sa Leboa" },
  { code: "nya", name: "Nyanja" },
  { code: "or", name: "Odia" },
  { code: "otq", name: "Queretaro Otomi" },
  { code: "pa", name: "Punjabi" },
  { code: "pl", name: "Polish" },
  { code: "prs", name: "Dari" },
  { code: "ps", name: "Pashto" },
  { code: "pt", name: "Portuguese (Brazil)" },
  { code: "pt-PT", name: "Portuguese (Portugal)" },
  { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" },
  { code: "run", name: "Rundi" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "sd", name: "Sindhi" },
  { code: "si", name: "Sinhala" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "sm", name: "Samoan" },
  { code: "sn", name: "Shona" },
  { code: "so", name: "Somali" },
  { code: "sq", name: "Albanian" },
  { code: "sr-Cyrl", name: "Serbian (Cyrillic)" },
  { code: "sr-Latn", name: "Serbian (Latin)" },
  { code: "st", name: "Sesotho" },
  { code: "sv", name: "Swedish" },
  { code: "sw", name: "Swahili" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "ti", name: "Tigrinya" },
  { code: "tk", name: "Turkmen" },
  { code: "tlh-Latn", name: "Klingon (Latin)" },
  { code: "tlh-Piqd", name: "Klingon (pIqaD)" },
  { code: "tn", name: "Setswana" },
  { code: "to", name: "Tongan" },
  { code: "tr", name: "Turkish" },
  { code: "tt", name: "Tatar" },
  { code: "ty", name: "Tahitian" },
  { code: "ug", name: "Uyghur" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "uz", name: "Uzbek (Latin)" },
  { code: "vi", name: "Vietnamese" },
  { code: "xh", name: "Xhosa" },
  { code: "yo", name: "Yoruba" },
  { code: "yua", name: "Yucatec Maya" },
  { code: "yue", name: "Cantonese (Traditional)" },
  { code: "zh-Hans", name: "Chinese Simplified" },
  { code: "zh-Hant", name: "Chinese Traditional" },
  { code: "zu", name: "Zulu" }
];

const deeplLanguages: Array<Omit<LanguageOption, "providers">> = [
  { code: "ar", name: "Arabic" },
  { code: "bg", name: "Bulgarian" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "de", name: "German" },
  { code: "de-CH", name: "German (Swiss)" },
  { code: "el", name: "Greek" },
  { code: "en", name: "English" },
  { code: "en-GB", name: "English (British)" },
  { code: "en-US", name: "English (American)" },
  { code: "es", name: "Spanish" },
  { code: "es-419", name: "Spanish (Latin American)" },
  { code: "et", name: "Estonian" },
  { code: "fi", name: "Finnish" },
  { code: "fr", name: "French" },
  { code: "fr-CA", name: "French (Canadian)" },
  { code: "hu", name: "Hungarian" },
  { code: "id", name: "Indonesian" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "lt", name: "Lithuanian" },
  { code: "lv", name: "Latvian" },
  { code: "nb", name: "Norwegian Bokmal" },
  { code: "nl", name: "Dutch" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "pt-BR", name: "Portuguese (Brazilian)" },
  { code: "pt-PT", name: "Portuguese (European)" },
  { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "sv", name: "Swedish" },
  { code: "tr", name: "Turkish" },
  { code: "uk", name: "Ukrainian" },
  { code: "zh", name: "Chinese" },
  { code: "zh-Hans", name: "Chinese (simplified)" },
  { code: "zh-Hant", name: "Chinese (traditional)" },
  { code: "ace", name: "Acehnese" },
  { code: "af", name: "Afrikaans" },
  { code: "an", name: "Aragonese" },
  { code: "as", name: "Assamese" },
  { code: "ay", name: "Aymara" },
  { code: "az", name: "Azerbaijani" },
  { code: "ba", name: "Bashkir" },
  { code: "be", name: "Belarusian" },
  { code: "bho", name: "Bhojpuri" },
  { code: "bn", name: "Bengali" },
  { code: "br", name: "Breton" },
  { code: "bs", name: "Bosnian" },
  { code: "ca", name: "Catalan" },
  { code: "ceb", name: "Cebuano" },
  { code: "ckb", name: "Kurdish (Sorani)" },
  { code: "cy", name: "Welsh" },
  { code: "eo", name: "Esperanto" },
  { code: "eu", name: "Basque" },
  { code: "fa", name: "Persian" },
  { code: "ga", name: "Irish" },
  { code: "gl", name: "Galician" },
  { code: "gn", name: "Guarani" },
  { code: "gom", name: "Konkani" },
  { code: "gu", name: "Gujarati" },
  { code: "ha", name: "Hausa" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hr", name: "Croatian" },
  { code: "ht", name: "Haitian Creole" },
  { code: "hy", name: "Armenian" },
  { code: "ig", name: "Igbo" },
  { code: "is", name: "Icelandic" },
  { code: "jv", name: "Javanese" },
  { code: "ka", name: "Georgian" },
  { code: "kk", name: "Kazakh" },
  { code: "kmr", name: "Kurdish (Kurmanji)" },
  { code: "ky", name: "Kyrgyz" },
  { code: "la", name: "Latin" },
  { code: "lb", name: "Luxembourgish" },
  { code: "lmo", name: "Lombard" },
  { code: "ln", name: "Lingala" },
  { code: "mai", name: "Maithili" },
  { code: "mg", name: "Malagasy" },
  { code: "mi", name: "Maori" },
  { code: "mk", name: "Macedonian" },
  { code: "ml", name: "Malayalam" },
  { code: "mn", name: "Mongolian" },
  { code: "mr", name: "Marathi" },
  { code: "ms", name: "Malay" },
  { code: "mt", name: "Maltese" },
  { code: "my", name: "Burmese" },
  { code: "ne", name: "Nepali" },
  { code: "oc", name: "Occitan" },
  { code: "om", name: "Oromo" },
  { code: "pa", name: "Punjabi" },
  { code: "pag", name: "Pangasinan" },
  { code: "pam", name: "Kapampangan" },
  { code: "prs", name: "Dari" },
  { code: "ps", name: "Pashto" },
  { code: "qu", name: "Quechua" },
  { code: "sa", name: "Sanskrit" },
  { code: "scn", name: "Sicilian" },
  { code: "sq", name: "Albanian" },
  { code: "sr", name: "Serbian" },
  { code: "st", name: "Sesotho" },
  { code: "su", name: "Sundanese" },
  { code: "sw", name: "Swahili" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "tg", name: "Tajik" },
  { code: "th", name: "Thai" },
  { code: "tk", name: "Turkmen" },
  { code: "tl", name: "Tagalog" },
  { code: "tn", name: "Tswana" },
  { code: "ts", name: "Tsonga" },
  { code: "tt", name: "Tatar" },
  { code: "ur", name: "Urdu" },
  { code: "uz", name: "Uzbek" },
  { code: "vi", name: "Vietnamese" },
  { code: "wo", name: "Wolof" },
  { code: "xh", name: "Xhosa" },
  { code: "yi", name: "Yiddish" },
  { code: "yue", name: "Cantonese" },
  { code: "zu", name: "Zulu" }
];

export const languageOptions: LanguageOption[] = createLanguageOptions();
export const defaultFavoriteLanguageCodes = ["en-GB", "de", "fr", "nb"];

export const sourceLanguageOptions: LanguageOption[] = [
  { code: "auto", name: "Auto detect", providers: ["microsoft", "deepl"], sourceOnly: true },
  ...languageOptions
];

export function findLanguageOption(code: string, includeAuto = false): LanguageOption | undefined {
  const options = includeAuto ? sourceLanguageOptions : languageOptions;
  return options.find((language) => language.code === code);
}

export function formatLanguageName(code: string, includeAuto = false): string {
  const language = findLanguageOption(code, includeAuto);
  return language ? `${language.name} (${language.code})` : code;
}

function createLanguageOptions(): LanguageOption[] {
  const map = new Map<string, LanguageOption>();
  for (const language of microsoftLanguages) {
    map.set(language.code, { ...language, providers: ["microsoft"] });
  }
  for (const language of deeplLanguages) {
    const existing = map.get(language.code);
    if (existing) {
      existing.providers = [...existing.providers, "deepl"];
      if (language.name.length < existing.name.length) {
        existing.name = language.name;
      }
    } else {
      map.set(language.code, { ...language, providers: ["deepl"] });
    }
  }

  return [...map.values()].sort((left, right) => left.name.localeCompare(right.name));
}
